# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityName', models.CharField(max_length=100, verbose_name='ActivityName')),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('Province', models.CharField(max_length=10, verbose_name='Province')),
                ('City', models.CharField(max_length=100, verbose_name='City')),
                ('Category', models.TextField(verbose_name='Category')),
                ('Description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
