# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161130_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
